{% set name = "netgraph" %}
{% set version = "4.12.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netgraph-{{ version }}.tar.gz
  sha256: 41ffb96034b4f02e7a0747aded60514bfb6248dc72a2ff537711491f02094f72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base >=1.5
    - rectangle-packer
    - grandalf

test:
  imports:
    - netgraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/paulbrodersen/netgraph
  summary: Python drawing utilities for publication quality plots of networks.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paulbrodersen
